---
global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: false
  insecure: false

ping: {}

accesslog:
  filePath: "/logs/traefik.log"
  format: json
  filters:
    statusCodes:
      - "200-299" # log successful http requests
      - "400-599" # log failed http requests
    retryAttempts: true
    #minDuration: "10ms"
  # Collect logs as in-memory buffer before writing into log file
  bufferingSize: 0
  fields:
    headers:
      defaultMode: drop # drop all headers per default
      names:
        User-Agent: keep # log user agent strings

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http3:
      advertisedPort: 443
    http:
      tls:
        certResolver: le
        # Definidos como environment no compose
        # domains:
        #   - main: example.com
        #     sans:
        #       - "*.example.com"
      middlewares:
        - security-headers@file
        - geoblock@file
        - crowdsec@file
        - rate-limit@file
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 10s
        graceTimeOut: 15s
      respondingTimeouts:
        readTimeout: 60s
        writeTimeout: 60s
        idleTimeout: 180s

experimental:
  plugins:
    geoblock:
      moduleName: github.com/PascalMinder/geoblock
      version: v0.3.3
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.6

providers:
  docker:
    exposedByDefault: false
    network: traefik
    watch: true
    endpoint: "tcp://socket-proxy:2375"

  file:
    directory: /etc/traefik/files
    watch: true

certificatesResolvers:
  le:
    acme:
      # Definido como environment no compose
      # email: email@example.com
      storage: /var/traefik/certs/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
